version: '3.9'
services:
  init_job:
    container_name: init_job
    image: blueinit/database-utils:1.0.1
    ports:
      - "80:80"
    environment:
      - IAM_USER=task
      - IAM_PASSWORD=task
      - DATABASE=tenant_management
      - QUERIES_FILE=/app/queries.sql
      - DEFAULT_DB_HOST=postgres
      - DEFAULT_DB_USER=postgres
      - DEFAULT_DB_PASSWORD=postgres
      - DEFAULT_DB=postgres
      - JOB_TRIGGERS=CREATE_USER,CREATE_DATABASE,GRANT_USER_DATABASE_ACCESS
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:15.2
    ports:
      - 5432:5432
    volumes:
      - ~/private/docker-volume/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres  
  pgadmin:
   container_name: pgadmin
   image: dpage/pgadmin4:latest
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: developers@blueinit.com
     PGADMIN_DEFAULT_PASSWORD: admin
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "8080:80"
   volumes:
     - ~/private/docker-volume/pgadmin-data:/var/lib/pgadmin    
